package com.rongseal.db.com.rongseal.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUP.
 */
public class Group {

    /** Not-null value. */
    private String groupId;
    private String name;
    private String portraitUri;
    private Short createTime;
    private String number;
    private Short createId;
    private Short introduce;

    public Group() {
    }

    public Group(String groupId) {
        this.groupId = groupId;
    }

    public Group(String groupId, String name, String portraitUri, Short createTime, String number, Short createId, Short introduce) {
        this.groupId = groupId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.createTime = createTime;
        this.number = number;
        this.createId = createId;
        this.introduce = introduce;
    }

    /** Not-null value. */
    public String getGroupId() {
        return groupId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    public Short getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Short createTime) {
        this.createTime = createTime;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public Short getCreateId() {
        return createId;
    }

    public void setCreateId(Short createId) {
        this.createId = createId;
    }

    public Short getIntroduce() {
        return introduce;
    }

    public void setIntroduce(Short introduce) {
        this.introduce = introduce;
    }

}
