package com.rongseal.db.com.rongseal.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    /** Not-null value. */
    private String userId;
    private String name;
    private String portraitUri;
    /** Not-null value. */
    private String token;
    private Boolean isFirstLogin;

    public User() {
    }

    public User(String userId) {
        this.userId = userId;
    }

    public User(String userId, String name, String portraitUri, String token, Boolean isFirstLogin) {
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.token = token;
        this.isFirstLogin = isFirstLogin;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    /** Not-null value. */
    public String getToken() {
        return token;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToken(String token) {
        this.token = token;
    }

    public Boolean getIsFirstLogin() {
        return isFirstLogin;
    }

    public void setIsFirstLogin(Boolean isFirstLogin) {
        this.isFirstLogin = isFirstLogin;
    }

}
